Attempt different method for ssh setup

diff --git a/.github/workflows/run-tests.yaml b/.github/workflows/run-tests.yaml
--- a/.github/workflows/run-tests.yaml
+++ b/.github/workflows/run-tests.yaml
@@ -206,11 +206,21 @@ jobs:
 
       - name: Setup environment
         run: |
-          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -P ""
-          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
-          chmod 0600 ~/.ssh/{authorized_keys,id_rsa,id_rsa.pub}
-          eval "$(ssh-agent -s)" #start the ssh agent
-          ssh-add
+          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
+          cat > ~/.ssh/config <<EOF
+          Host host.example
+            User $USER
+            HostName 127.0.0.1
+            IdentityFile ~/.ssh/id_ed25519
+          EOF
+          echo -n 'from="127.0.0.1" ' | cat - ~/.ssh/id_ed25519.pub > ~/.ssh/authorized_keys
+          echo "Before fixing permissions on authorized_keys, notice home directory is world read/write"
+          ls -la ~/.ssh
+          ssh -o 'StrictHostKeyChecking no' host.example id || echo "ssh failed as expected... trying to fix permissions"
+          chmod og-rw ~
+          echo "After fixing permissions on home folder ~ ..."
+          ls -la ~/.ssh
+          ssh -o 'StrictHostKeyChecking no' host.example id
 
       - name: Install dependencies
         run: |
